// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: account.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lampyris.Crypto.Protocol.Account {

  /// <summary>Holder for reflection information generated from account.proto</summary>
  public static partial class AccountReflection {

    #region Descriptor
    /// <summary>File descriptor for account.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AccountReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1hY2NvdW50LnByb3RvEiBsYW1weXJpcy5jcnlwdG8ucHJvdG9jb2wuYWNj",
            "b3VudCK4AQoUQWNjb3VudEFzc2V0SW5mb0JlYW4SDwoHYmFsYW5jZRgBIAEo",
            "ARIVCg1wb3NpdGlvblZhbHVlGAIgASgBEhUKDXVucmVhbGl6ZWRQbkwYAyAB",
            "KAESEAoIZGFpbHlQbkwYBCABKAESGgoSZGFpbHlQbkxQZXJjZW50YWdlGAUg",
            "ASgBEhgKEGF2YWlsYWJsZUJhbGFuY2UYBiABKAESGQoRbWF4V2l0aGRyYXdB",
            "bW91bnQYByABKAEiwwEKElN1YkFjY291bnRJbmZvQmVhbhIRCglhY2NvdW50",
            "SWQYASABKAUSSQoJYXNzZXRJbmZvGAIgASgLMjYubGFtcHlyaXMuY3J5cHRv",
            "LnByb3RvY29sLmFjY291bnQuQWNjb3VudEFzc2V0SW5mb0JlYW4SEQoJb3du",
            "ZXJOYW1lGAMgASgJEhIKCm93bmVyRW1haWwYBCABKAkSGAoQb3duZXJQaG9u",
            "ZU51bWJlchgFIAEoCRIOCgZpc1Jvb3QYBiABKAgiYQoXUmVzUXVlcnlTdWJB",
            "Y2Njb3VudExpc3QSRgoIYmVhbkxpc3QYASABKAsyNC5sYW1weXJpcy5jcnlw",
            "dG8ucHJvdG9jb2wuYWNjb3VudC5TdWJBY2NvdW50SW5mb0JlYW4iKwoXUmVx",
            "QWNjb3VudFN1bW1hcnlVcGRhdGUSEAoIaXNDYW5jZWwYASABKAgiZAoXUmVz",
            "QWNjb3VudFN1bW1hcnlVcGRhdGUSSQoJYXNzZXRJbmZvGAEgASgLMjYubGFt",
            "cHlyaXMuY3J5cHRvLnByb3RvY29sLmFjY291bnQuQWNjb3VudEFzc2V0SW5m",
            "b0JlYW4iXAoXUmVxQWNjb3VudEFzc2V0VHJhbnNmZXISQQoEdHlwZRgBIAEo",
            "DjIzLmxhbXB5cmlzLmNyeXB0by5wcm90b2NvbC5hY2NvdW50LkFzc2V0VHJh",
            "bnNmZXJUeXBlImYKIkFzc2V0VHJhbnNmZXJIaXN0b3J5SW5mb0RldGFpbEJl",
            "YW4SFwoPc291cmNlQWNjb3VudElkGAEgASgFEhcKD3RhcmdldEFjY291bnRJ",
            "ZBgCIAEoBRIOCgZhbW91bnQYAyABKAEiggIKHEFzc2V0VHJhbnNmZXJIaXN0",
            "b3J5SW5mb0JlYW4SQQoEdHlwZRgBIAEoDjIzLmxhbXB5cmlzLmNyeXB0by5w",
            "cm90b2NvbC5hY2NvdW50LkFzc2V0VHJhbnNmZXJUeXBlElwKDmRldGFpbEJl",
            "YW5MaXN0GAIgAygLMkQubGFtcHlyaXMuY3J5cHRvLnByb3RvY29sLmFjY291",
            "bnQuQXNzZXRUcmFuc2Zlckhpc3RvcnlJbmZvRGV0YWlsQmVhbhIeChZ0cmFu",
            "c2ZlclN0YXJ0VGltZXN0YW1wGAMgASgDEiEKGXRyYW5zZmVyRmluaXNoZWRU",
            "aW1lc3RhbXAYBCABKAMiHgocUmVxUXVlcnlBc3NldFRyYW5zZmVySGlzdG9y",
            "eSpcChFBc3NldFRyYW5zZmVyVHlwZRIbChdSRV9BVkdFUkFHRV9TVUJfQUND",
            "T1VOVBAAEhMKD1RPX1JPT1RfQUNDT1VOVBABEhUKEVRPX1dBTExFVF9BQ0NP",
            "VU5UEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Lampyris.Crypto.Protocol.Account.AssetTransferType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Lampyris.Crypto.Protocol.Account.AccountAssetInfoBean), global::Lampyris.Crypto.Protocol.Account.AccountAssetInfoBean.Parser, new[]{ "Balance", "PositionValue", "UnrealizedPnL", "DailyPnL", "DailyPnLPercentage", "AvailableBalance", "MaxWithdrawAmount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Lampyris.Crypto.Protocol.Account.SubAccountInfoBean), global::Lampyris.Crypto.Protocol.Account.SubAccountInfoBean.Parser, new[]{ "AccountId", "AssetInfo", "OwnerName", "OwnerEmail", "OwnerPhoneNumber", "IsRoot" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Lampyris.Crypto.Protocol.Account.ResQuerySubAcccountList), global::Lampyris.Crypto.Protocol.Account.ResQuerySubAcccountList.Parser, new[]{ "BeanList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Lampyris.Crypto.Protocol.Account.ReqAccountSummaryUpdate), global::Lampyris.Crypto.Protocol.Account.ReqAccountSummaryUpdate.Parser, new[]{ "IsCancel" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Lampyris.Crypto.Protocol.Account.ResAccountSummaryUpdate), global::Lampyris.Crypto.Protocol.Account.ResAccountSummaryUpdate.Parser, new[]{ "AssetInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Lampyris.Crypto.Protocol.Account.ReqAccountAssetTransfer), global::Lampyris.Crypto.Protocol.Account.ReqAccountAssetTransfer.Parser, new[]{ "Type" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Lampyris.Crypto.Protocol.Account.AssetTransferHistoryInfoDetailBean), global::Lampyris.Crypto.Protocol.Account.AssetTransferHistoryInfoDetailBean.Parser, new[]{ "SourceAccountId", "TargetAccountId", "Amount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Lampyris.Crypto.Protocol.Account.AssetTransferHistoryInfoBean), global::Lampyris.Crypto.Protocol.Account.AssetTransferHistoryInfoBean.Parser, new[]{ "Type", "DetailBeanList", "TransferStartTimestamp", "TransferFinishedTimestamp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Lampyris.Crypto.Protocol.Account.ReqQueryAssetTransferHistory), global::Lampyris.Crypto.Protocol.Account.ReqQueryAssetTransferHistory.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum AssetTransferType {
    /// <summary>
    /// 子账户资产再平均
    /// </summary>
    [pbr::OriginalName("RE_AVGERAGE_SUB_ACCOUNT")] ReAvgerageSubAccount = 0,
    /// <summary>
    /// 子账户转移到根账户
    /// </summary>
    [pbr::OriginalName("TO_ROOT_ACCOUNT")] ToRootAccount = 1,
    /// <summary>
    /// 根账户到钱包账户
    /// </summary>
    [pbr::OriginalName("TO_WALLET_ACCOUNT")] ToWalletAccount = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AccountAssetInfoBean : pb::IMessage<AccountAssetInfoBean>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AccountAssetInfoBean> _parser = new pb::MessageParser<AccountAssetInfoBean>(() => new AccountAssetInfoBean());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AccountAssetInfoBean> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lampyris.Crypto.Protocol.Account.AccountReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccountAssetInfoBean() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccountAssetInfoBean(AccountAssetInfoBean other) : this() {
      balance_ = other.balance_;
      positionValue_ = other.positionValue_;
      unrealizedPnL_ = other.unrealizedPnL_;
      dailyPnL_ = other.dailyPnL_;
      dailyPnLPercentage_ = other.dailyPnLPercentage_;
      availableBalance_ = other.availableBalance_;
      maxWithdrawAmount_ = other.maxWithdrawAmount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccountAssetInfoBean Clone() {
      return new AccountAssetInfoBean(this);
    }

    /// <summary>Field number for the "balance" field.</summary>
    public const int BalanceFieldNumber = 1;
    private double balance_;
    /// <summary>
    /// 资产数(USDT)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Balance {
      get { return balance_; }
      set {
        balance_ = value;
      }
    }

    /// <summary>Field number for the "positionValue" field.</summary>
    public const int PositionValueFieldNumber = 2;
    private double positionValue_;
    /// <summary>
    /// 持仓价值(USDT)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double PositionValue {
      get { return positionValue_; }
      set {
        positionValue_ = value;
      }
    }

    /// <summary>Field number for the "unrealizedPnL" field.</summary>
    public const int UnrealizedPnLFieldNumber = 3;
    private double unrealizedPnL_;
    /// <summary>
    /// 未实现盈亏(USDT)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double UnrealizedPnL {
      get { return unrealizedPnL_; }
      set {
        unrealizedPnL_ = value;
      }
    }

    /// <summary>Field number for the "dailyPnL" field.</summary>
    public const int DailyPnLFieldNumber = 4;
    private double dailyPnL_;
    /// <summary>
    /// 今日盈亏(USDT)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double DailyPnL {
      get { return dailyPnL_; }
      set {
        dailyPnL_ = value;
      }
    }

    /// <summary>Field number for the "dailyPnLPercentage" field.</summary>
    public const int DailyPnLPercentageFieldNumber = 5;
    private double dailyPnLPercentage_;
    /// <summary>
    /// 今日盈亏比例(%)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double DailyPnLPercentage {
      get { return dailyPnLPercentage_; }
      set {
        dailyPnLPercentage_ = value;
      }
    }

    /// <summary>Field number for the "availableBalance" field.</summary>
    public const int AvailableBalanceFieldNumber = 6;
    private double availableBalance_;
    /// <summary>
    /// 可用资金(USDT)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double AvailableBalance {
      get { return availableBalance_; }
      set {
        availableBalance_ = value;
      }
    }

    /// <summary>Field number for the "maxWithdrawAmount" field.</summary>
    public const int MaxWithdrawAmountFieldNumber = 7;
    private double maxWithdrawAmount_;
    /// <summary>
    /// 最大可转出数目(USDT)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double MaxWithdrawAmount {
      get { return maxWithdrawAmount_; }
      set {
        maxWithdrawAmount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AccountAssetInfoBean);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AccountAssetInfoBean other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Balance, other.Balance)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(PositionValue, other.PositionValue)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(UnrealizedPnL, other.UnrealizedPnL)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DailyPnL, other.DailyPnL)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DailyPnLPercentage, other.DailyPnLPercentage)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(AvailableBalance, other.AvailableBalance)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(MaxWithdrawAmount, other.MaxWithdrawAmount)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Balance != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Balance);
      if (PositionValue != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(PositionValue);
      if (UnrealizedPnL != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(UnrealizedPnL);
      if (DailyPnL != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DailyPnL);
      if (DailyPnLPercentage != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DailyPnLPercentage);
      if (AvailableBalance != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(AvailableBalance);
      if (MaxWithdrawAmount != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(MaxWithdrawAmount);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Balance != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Balance);
      }
      if (PositionValue != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(PositionValue);
      }
      if (UnrealizedPnL != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(UnrealizedPnL);
      }
      if (DailyPnL != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(DailyPnL);
      }
      if (DailyPnLPercentage != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(DailyPnLPercentage);
      }
      if (AvailableBalance != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(AvailableBalance);
      }
      if (MaxWithdrawAmount != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(MaxWithdrawAmount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Balance != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Balance);
      }
      if (PositionValue != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(PositionValue);
      }
      if (UnrealizedPnL != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(UnrealizedPnL);
      }
      if (DailyPnL != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(DailyPnL);
      }
      if (DailyPnLPercentage != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(DailyPnLPercentage);
      }
      if (AvailableBalance != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(AvailableBalance);
      }
      if (MaxWithdrawAmount != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(MaxWithdrawAmount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Balance != 0D) {
        size += 1 + 8;
      }
      if (PositionValue != 0D) {
        size += 1 + 8;
      }
      if (UnrealizedPnL != 0D) {
        size += 1 + 8;
      }
      if (DailyPnL != 0D) {
        size += 1 + 8;
      }
      if (DailyPnLPercentage != 0D) {
        size += 1 + 8;
      }
      if (AvailableBalance != 0D) {
        size += 1 + 8;
      }
      if (MaxWithdrawAmount != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AccountAssetInfoBean other) {
      if (other == null) {
        return;
      }
      if (other.Balance != 0D) {
        Balance = other.Balance;
      }
      if (other.PositionValue != 0D) {
        PositionValue = other.PositionValue;
      }
      if (other.UnrealizedPnL != 0D) {
        UnrealizedPnL = other.UnrealizedPnL;
      }
      if (other.DailyPnL != 0D) {
        DailyPnL = other.DailyPnL;
      }
      if (other.DailyPnLPercentage != 0D) {
        DailyPnLPercentage = other.DailyPnLPercentage;
      }
      if (other.AvailableBalance != 0D) {
        AvailableBalance = other.AvailableBalance;
      }
      if (other.MaxWithdrawAmount != 0D) {
        MaxWithdrawAmount = other.MaxWithdrawAmount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Balance = input.ReadDouble();
            break;
          }
          case 17: {
            PositionValue = input.ReadDouble();
            break;
          }
          case 25: {
            UnrealizedPnL = input.ReadDouble();
            break;
          }
          case 33: {
            DailyPnL = input.ReadDouble();
            break;
          }
          case 41: {
            DailyPnLPercentage = input.ReadDouble();
            break;
          }
          case 49: {
            AvailableBalance = input.ReadDouble();
            break;
          }
          case 57: {
            MaxWithdrawAmount = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Balance = input.ReadDouble();
            break;
          }
          case 17: {
            PositionValue = input.ReadDouble();
            break;
          }
          case 25: {
            UnrealizedPnL = input.ReadDouble();
            break;
          }
          case 33: {
            DailyPnL = input.ReadDouble();
            break;
          }
          case 41: {
            DailyPnLPercentage = input.ReadDouble();
            break;
          }
          case 49: {
            AvailableBalance = input.ReadDouble();
            break;
          }
          case 57: {
            MaxWithdrawAmount = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SubAccountInfoBean : pb::IMessage<SubAccountInfoBean>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SubAccountInfoBean> _parser = new pb::MessageParser<SubAccountInfoBean>(() => new SubAccountInfoBean());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SubAccountInfoBean> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lampyris.Crypto.Protocol.Account.AccountReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubAccountInfoBean() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubAccountInfoBean(SubAccountInfoBean other) : this() {
      accountId_ = other.accountId_;
      assetInfo_ = other.assetInfo_ != null ? other.assetInfo_.Clone() : null;
      ownerName_ = other.ownerName_;
      ownerEmail_ = other.ownerEmail_;
      ownerPhoneNumber_ = other.ownerPhoneNumber_;
      isRoot_ = other.isRoot_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubAccountInfoBean Clone() {
      return new SubAccountInfoBean(this);
    }

    /// <summary>Field number for the "accountId" field.</summary>
    public const int AccountIdFieldNumber = 1;
    private int accountId_;
    /// <summary>
    /// 子账户ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AccountId {
      get { return accountId_; }
      set {
        accountId_ = value;
      }
    }

    /// <summary>Field number for the "assetInfo" field.</summary>
    public const int AssetInfoFieldNumber = 2;
    private global::Lampyris.Crypto.Protocol.Account.AccountAssetInfoBean assetInfo_;
    /// <summary>
    /// 子账户拥有的资产信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Lampyris.Crypto.Protocol.Account.AccountAssetInfoBean AssetInfo {
      get { return assetInfo_; }
      set {
        assetInfo_ = value;
      }
    }

    /// <summary>Field number for the "ownerName" field.</summary>
    public const int OwnerNameFieldNumber = 3;
    private string ownerName_ = "";
    /// <summary>
    /// 账户拥有者名称(便于沟通)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OwnerName {
      get { return ownerName_; }
      set {
        ownerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ownerEmail" field.</summary>
    public const int OwnerEmailFieldNumber = 4;
    private string ownerEmail_ = "";
    /// <summary>
    /// 账户拥有者邮箱地址
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OwnerEmail {
      get { return ownerEmail_; }
      set {
        ownerEmail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ownerPhoneNumber" field.</summary>
    public const int OwnerPhoneNumberFieldNumber = 5;
    private string ownerPhoneNumber_ = "";
    /// <summary>
    /// 账户拥有者手机号码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OwnerPhoneNumber {
      get { return ownerPhoneNumber_; }
      set {
        ownerPhoneNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isRoot" field.</summary>
    public const int IsRootFieldNumber = 6;
    private bool isRoot_;
    /// <summary>
    /// 是否根账户，这涉及到资金的转移
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsRoot {
      get { return isRoot_; }
      set {
        isRoot_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SubAccountInfoBean);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SubAccountInfoBean other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AccountId != other.AccountId) return false;
      if (!object.Equals(AssetInfo, other.AssetInfo)) return false;
      if (OwnerName != other.OwnerName) return false;
      if (OwnerEmail != other.OwnerEmail) return false;
      if (OwnerPhoneNumber != other.OwnerPhoneNumber) return false;
      if (IsRoot != other.IsRoot) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AccountId != 0) hash ^= AccountId.GetHashCode();
      if (assetInfo_ != null) hash ^= AssetInfo.GetHashCode();
      if (OwnerName.Length != 0) hash ^= OwnerName.GetHashCode();
      if (OwnerEmail.Length != 0) hash ^= OwnerEmail.GetHashCode();
      if (OwnerPhoneNumber.Length != 0) hash ^= OwnerPhoneNumber.GetHashCode();
      if (IsRoot != false) hash ^= IsRoot.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AccountId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AccountId);
      }
      if (assetInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AssetInfo);
      }
      if (OwnerName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OwnerName);
      }
      if (OwnerEmail.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OwnerEmail);
      }
      if (OwnerPhoneNumber.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(OwnerPhoneNumber);
      }
      if (IsRoot != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsRoot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AccountId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AccountId);
      }
      if (assetInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AssetInfo);
      }
      if (OwnerName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OwnerName);
      }
      if (OwnerEmail.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OwnerEmail);
      }
      if (OwnerPhoneNumber.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(OwnerPhoneNumber);
      }
      if (IsRoot != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsRoot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AccountId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AccountId);
      }
      if (assetInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AssetInfo);
      }
      if (OwnerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OwnerName);
      }
      if (OwnerEmail.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OwnerEmail);
      }
      if (OwnerPhoneNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OwnerPhoneNumber);
      }
      if (IsRoot != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SubAccountInfoBean other) {
      if (other == null) {
        return;
      }
      if (other.AccountId != 0) {
        AccountId = other.AccountId;
      }
      if (other.assetInfo_ != null) {
        if (assetInfo_ == null) {
          AssetInfo = new global::Lampyris.Crypto.Protocol.Account.AccountAssetInfoBean();
        }
        AssetInfo.MergeFrom(other.AssetInfo);
      }
      if (other.OwnerName.Length != 0) {
        OwnerName = other.OwnerName;
      }
      if (other.OwnerEmail.Length != 0) {
        OwnerEmail = other.OwnerEmail;
      }
      if (other.OwnerPhoneNumber.Length != 0) {
        OwnerPhoneNumber = other.OwnerPhoneNumber;
      }
      if (other.IsRoot != false) {
        IsRoot = other.IsRoot;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AccountId = input.ReadInt32();
            break;
          }
          case 18: {
            if (assetInfo_ == null) {
              AssetInfo = new global::Lampyris.Crypto.Protocol.Account.AccountAssetInfoBean();
            }
            input.ReadMessage(AssetInfo);
            break;
          }
          case 26: {
            OwnerName = input.ReadString();
            break;
          }
          case 34: {
            OwnerEmail = input.ReadString();
            break;
          }
          case 42: {
            OwnerPhoneNumber = input.ReadString();
            break;
          }
          case 48: {
            IsRoot = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AccountId = input.ReadInt32();
            break;
          }
          case 18: {
            if (assetInfo_ == null) {
              AssetInfo = new global::Lampyris.Crypto.Protocol.Account.AccountAssetInfoBean();
            }
            input.ReadMessage(AssetInfo);
            break;
          }
          case 26: {
            OwnerName = input.ReadString();
            break;
          }
          case 34: {
            OwnerEmail = input.ReadString();
            break;
          }
          case 42: {
            OwnerPhoneNumber = input.ReadString();
            break;
          }
          case 48: {
            IsRoot = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResQuerySubAcccountList : pb::IMessage<ResQuerySubAcccountList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResQuerySubAcccountList> _parser = new pb::MessageParser<ResQuerySubAcccountList>(() => new ResQuerySubAcccountList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResQuerySubAcccountList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lampyris.Crypto.Protocol.Account.AccountReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResQuerySubAcccountList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResQuerySubAcccountList(ResQuerySubAcccountList other) : this() {
      beanList_ = other.beanList_ != null ? other.beanList_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResQuerySubAcccountList Clone() {
      return new ResQuerySubAcccountList(this);
    }

    /// <summary>Field number for the "beanList" field.</summary>
    public const int BeanListFieldNumber = 1;
    private global::Lampyris.Crypto.Protocol.Account.SubAccountInfoBean beanList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Lampyris.Crypto.Protocol.Account.SubAccountInfoBean BeanList {
      get { return beanList_; }
      set {
        beanList_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResQuerySubAcccountList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResQuerySubAcccountList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BeanList, other.BeanList)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (beanList_ != null) hash ^= BeanList.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (beanList_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BeanList);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (beanList_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BeanList);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (beanList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BeanList);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResQuerySubAcccountList other) {
      if (other == null) {
        return;
      }
      if (other.beanList_ != null) {
        if (beanList_ == null) {
          BeanList = new global::Lampyris.Crypto.Protocol.Account.SubAccountInfoBean();
        }
        BeanList.MergeFrom(other.BeanList);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (beanList_ == null) {
              BeanList = new global::Lampyris.Crypto.Protocol.Account.SubAccountInfoBean();
            }
            input.ReadMessage(BeanList);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (beanList_ == null) {
              BeanList = new global::Lampyris.Crypto.Protocol.Account.SubAccountInfoBean();
            }
            input.ReadMessage(BeanList);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ReqAccountSummaryUpdate : pb::IMessage<ReqAccountSummaryUpdate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ReqAccountSummaryUpdate> _parser = new pb::MessageParser<ReqAccountSummaryUpdate>(() => new ReqAccountSummaryUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ReqAccountSummaryUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lampyris.Crypto.Protocol.Account.AccountReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReqAccountSummaryUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReqAccountSummaryUpdate(ReqAccountSummaryUpdate other) : this() {
      isCancel_ = other.isCancel_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReqAccountSummaryUpdate Clone() {
      return new ReqAccountSummaryUpdate(this);
    }

    /// <summary>Field number for the "isCancel" field.</summary>
    public const int IsCancelFieldNumber = 1;
    private bool isCancel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsCancel {
      get { return isCancel_; }
      set {
        isCancel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ReqAccountSummaryUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ReqAccountSummaryUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsCancel != other.IsCancel) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IsCancel != false) hash ^= IsCancel.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IsCancel != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsCancel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IsCancel != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsCancel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IsCancel != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ReqAccountSummaryUpdate other) {
      if (other == null) {
        return;
      }
      if (other.IsCancel != false) {
        IsCancel = other.IsCancel;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsCancel = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IsCancel = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResAccountSummaryUpdate : pb::IMessage<ResAccountSummaryUpdate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResAccountSummaryUpdate> _parser = new pb::MessageParser<ResAccountSummaryUpdate>(() => new ResAccountSummaryUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResAccountSummaryUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lampyris.Crypto.Protocol.Account.AccountReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResAccountSummaryUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResAccountSummaryUpdate(ResAccountSummaryUpdate other) : this() {
      assetInfo_ = other.assetInfo_ != null ? other.assetInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResAccountSummaryUpdate Clone() {
      return new ResAccountSummaryUpdate(this);
    }

    /// <summary>Field number for the "assetInfo" field.</summary>
    public const int AssetInfoFieldNumber = 1;
    private global::Lampyris.Crypto.Protocol.Account.AccountAssetInfoBean assetInfo_;
    /// <summary>
    /// 账户拥有的资产信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Lampyris.Crypto.Protocol.Account.AccountAssetInfoBean AssetInfo {
      get { return assetInfo_; }
      set {
        assetInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResAccountSummaryUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResAccountSummaryUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AssetInfo, other.AssetInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (assetInfo_ != null) hash ^= AssetInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (assetInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AssetInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (assetInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AssetInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (assetInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AssetInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResAccountSummaryUpdate other) {
      if (other == null) {
        return;
      }
      if (other.assetInfo_ != null) {
        if (assetInfo_ == null) {
          AssetInfo = new global::Lampyris.Crypto.Protocol.Account.AccountAssetInfoBean();
        }
        AssetInfo.MergeFrom(other.AssetInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (assetInfo_ == null) {
              AssetInfo = new global::Lampyris.Crypto.Protocol.Account.AccountAssetInfoBean();
            }
            input.ReadMessage(AssetInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (assetInfo_ == null) {
              AssetInfo = new global::Lampyris.Crypto.Protocol.Account.AccountAssetInfoBean();
            }
            input.ReadMessage(AssetInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ReqAccountAssetTransfer : pb::IMessage<ReqAccountAssetTransfer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ReqAccountAssetTransfer> _parser = new pb::MessageParser<ReqAccountAssetTransfer>(() => new ReqAccountAssetTransfer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ReqAccountAssetTransfer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lampyris.Crypto.Protocol.Account.AccountReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReqAccountAssetTransfer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReqAccountAssetTransfer(ReqAccountAssetTransfer other) : this() {
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReqAccountAssetTransfer Clone() {
      return new ReqAccountAssetTransfer(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Lampyris.Crypto.Protocol.Account.AssetTransferType type_ = global::Lampyris.Crypto.Protocol.Account.AssetTransferType.ReAvgerageSubAccount;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Lampyris.Crypto.Protocol.Account.AssetTransferType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ReqAccountAssetTransfer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ReqAccountAssetTransfer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Lampyris.Crypto.Protocol.Account.AssetTransferType.ReAvgerageSubAccount) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Lampyris.Crypto.Protocol.Account.AssetTransferType.ReAvgerageSubAccount) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Lampyris.Crypto.Protocol.Account.AssetTransferType.ReAvgerageSubAccount) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Lampyris.Crypto.Protocol.Account.AssetTransferType.ReAvgerageSubAccount) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ReqAccountAssetTransfer other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Lampyris.Crypto.Protocol.Account.AssetTransferType.ReAvgerageSubAccount) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Lampyris.Crypto.Protocol.Account.AssetTransferType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Lampyris.Crypto.Protocol.Account.AssetTransferType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AssetTransferHistoryInfoDetailBean : pb::IMessage<AssetTransferHistoryInfoDetailBean>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AssetTransferHistoryInfoDetailBean> _parser = new pb::MessageParser<AssetTransferHistoryInfoDetailBean>(() => new AssetTransferHistoryInfoDetailBean());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AssetTransferHistoryInfoDetailBean> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lampyris.Crypto.Protocol.Account.AccountReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AssetTransferHistoryInfoDetailBean() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AssetTransferHistoryInfoDetailBean(AssetTransferHistoryInfoDetailBean other) : this() {
      sourceAccountId_ = other.sourceAccountId_;
      targetAccountId_ = other.targetAccountId_;
      amount_ = other.amount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AssetTransferHistoryInfoDetailBean Clone() {
      return new AssetTransferHistoryInfoDetailBean(this);
    }

    /// <summary>Field number for the "sourceAccountId" field.</summary>
    public const int SourceAccountIdFieldNumber = 1;
    private int sourceAccountId_;
    /// <summary>
    /// 源账户ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SourceAccountId {
      get { return sourceAccountId_; }
      set {
        sourceAccountId_ = value;
      }
    }

    /// <summary>Field number for the "targetAccountId" field.</summary>
    public const int TargetAccountIdFieldNumber = 2;
    private int targetAccountId_;
    /// <summary>
    /// 目标账户ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TargetAccountId {
      get { return targetAccountId_; }
      set {
        targetAccountId_ = value;
      }
    }

    /// <summary>Field number for the "amount" field.</summary>
    public const int AmountFieldNumber = 3;
    private double amount_;
    /// <summary>
    /// 数量(USDT) 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Amount {
      get { return amount_; }
      set {
        amount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AssetTransferHistoryInfoDetailBean);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AssetTransferHistoryInfoDetailBean other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SourceAccountId != other.SourceAccountId) return false;
      if (TargetAccountId != other.TargetAccountId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Amount, other.Amount)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SourceAccountId != 0) hash ^= SourceAccountId.GetHashCode();
      if (TargetAccountId != 0) hash ^= TargetAccountId.GetHashCode();
      if (Amount != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Amount);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SourceAccountId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SourceAccountId);
      }
      if (TargetAccountId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TargetAccountId);
      }
      if (Amount != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Amount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SourceAccountId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SourceAccountId);
      }
      if (TargetAccountId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TargetAccountId);
      }
      if (Amount != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Amount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SourceAccountId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SourceAccountId);
      }
      if (TargetAccountId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetAccountId);
      }
      if (Amount != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AssetTransferHistoryInfoDetailBean other) {
      if (other == null) {
        return;
      }
      if (other.SourceAccountId != 0) {
        SourceAccountId = other.SourceAccountId;
      }
      if (other.TargetAccountId != 0) {
        TargetAccountId = other.TargetAccountId;
      }
      if (other.Amount != 0D) {
        Amount = other.Amount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SourceAccountId = input.ReadInt32();
            break;
          }
          case 16: {
            TargetAccountId = input.ReadInt32();
            break;
          }
          case 25: {
            Amount = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SourceAccountId = input.ReadInt32();
            break;
          }
          case 16: {
            TargetAccountId = input.ReadInt32();
            break;
          }
          case 25: {
            Amount = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AssetTransferHistoryInfoBean : pb::IMessage<AssetTransferHistoryInfoBean>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AssetTransferHistoryInfoBean> _parser = new pb::MessageParser<AssetTransferHistoryInfoBean>(() => new AssetTransferHistoryInfoBean());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AssetTransferHistoryInfoBean> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lampyris.Crypto.Protocol.Account.AccountReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AssetTransferHistoryInfoBean() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AssetTransferHistoryInfoBean(AssetTransferHistoryInfoBean other) : this() {
      type_ = other.type_;
      detailBeanList_ = other.detailBeanList_.Clone();
      transferStartTimestamp_ = other.transferStartTimestamp_;
      transferFinishedTimestamp_ = other.transferFinishedTimestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AssetTransferHistoryInfoBean Clone() {
      return new AssetTransferHistoryInfoBean(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Lampyris.Crypto.Protocol.Account.AssetTransferType type_ = global::Lampyris.Crypto.Protocol.Account.AssetTransferType.ReAvgerageSubAccount;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Lampyris.Crypto.Protocol.Account.AssetTransferType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "detailBeanList" field.</summary>
    public const int DetailBeanListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Lampyris.Crypto.Protocol.Account.AssetTransferHistoryInfoDetailBean> _repeated_detailBeanList_codec
        = pb::FieldCodec.ForMessage(18, global::Lampyris.Crypto.Protocol.Account.AssetTransferHistoryInfoDetailBean.Parser);
    private readonly pbc::RepeatedField<global::Lampyris.Crypto.Protocol.Account.AssetTransferHistoryInfoDetailBean> detailBeanList_ = new pbc::RepeatedField<global::Lampyris.Crypto.Protocol.Account.AssetTransferHistoryInfoDetailBean>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Lampyris.Crypto.Protocol.Account.AssetTransferHistoryInfoDetailBean> DetailBeanList {
      get { return detailBeanList_; }
    }

    /// <summary>Field number for the "transferStartTimestamp" field.</summary>
    public const int TransferStartTimestampFieldNumber = 3;
    private long transferStartTimestamp_;
    /// <summary>
    /// 发起时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TransferStartTimestamp {
      get { return transferStartTimestamp_; }
      set {
        transferStartTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "transferFinishedTimestamp" field.</summary>
    public const int TransferFinishedTimestampFieldNumber = 4;
    private long transferFinishedTimestamp_;
    /// <summary>
    /// 完成时间(如果没完成则为-1)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TransferFinishedTimestamp {
      get { return transferFinishedTimestamp_; }
      set {
        transferFinishedTimestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AssetTransferHistoryInfoBean);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AssetTransferHistoryInfoBean other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if(!detailBeanList_.Equals(other.detailBeanList_)) return false;
      if (TransferStartTimestamp != other.TransferStartTimestamp) return false;
      if (TransferFinishedTimestamp != other.TransferFinishedTimestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Lampyris.Crypto.Protocol.Account.AssetTransferType.ReAvgerageSubAccount) hash ^= Type.GetHashCode();
      hash ^= detailBeanList_.GetHashCode();
      if (TransferStartTimestamp != 0L) hash ^= TransferStartTimestamp.GetHashCode();
      if (TransferFinishedTimestamp != 0L) hash ^= TransferFinishedTimestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Lampyris.Crypto.Protocol.Account.AssetTransferType.ReAvgerageSubAccount) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      detailBeanList_.WriteTo(output, _repeated_detailBeanList_codec);
      if (TransferStartTimestamp != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TransferStartTimestamp);
      }
      if (TransferFinishedTimestamp != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TransferFinishedTimestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Lampyris.Crypto.Protocol.Account.AssetTransferType.ReAvgerageSubAccount) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      detailBeanList_.WriteTo(ref output, _repeated_detailBeanList_codec);
      if (TransferStartTimestamp != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TransferStartTimestamp);
      }
      if (TransferFinishedTimestamp != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TransferFinishedTimestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Lampyris.Crypto.Protocol.Account.AssetTransferType.ReAvgerageSubAccount) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      size += detailBeanList_.CalculateSize(_repeated_detailBeanList_codec);
      if (TransferStartTimestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TransferStartTimestamp);
      }
      if (TransferFinishedTimestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TransferFinishedTimestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AssetTransferHistoryInfoBean other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Lampyris.Crypto.Protocol.Account.AssetTransferType.ReAvgerageSubAccount) {
        Type = other.Type;
      }
      detailBeanList_.Add(other.detailBeanList_);
      if (other.TransferStartTimestamp != 0L) {
        TransferStartTimestamp = other.TransferStartTimestamp;
      }
      if (other.TransferFinishedTimestamp != 0L) {
        TransferFinishedTimestamp = other.TransferFinishedTimestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Lampyris.Crypto.Protocol.Account.AssetTransferType) input.ReadEnum();
            break;
          }
          case 18: {
            detailBeanList_.AddEntriesFrom(input, _repeated_detailBeanList_codec);
            break;
          }
          case 24: {
            TransferStartTimestamp = input.ReadInt64();
            break;
          }
          case 32: {
            TransferFinishedTimestamp = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Lampyris.Crypto.Protocol.Account.AssetTransferType) input.ReadEnum();
            break;
          }
          case 18: {
            detailBeanList_.AddEntriesFrom(ref input, _repeated_detailBeanList_codec);
            break;
          }
          case 24: {
            TransferStartTimestamp = input.ReadInt64();
            break;
          }
          case 32: {
            TransferFinishedTimestamp = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ReqQueryAssetTransferHistory : pb::IMessage<ReqQueryAssetTransferHistory>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ReqQueryAssetTransferHistory> _parser = new pb::MessageParser<ReqQueryAssetTransferHistory>(() => new ReqQueryAssetTransferHistory());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ReqQueryAssetTransferHistory> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lampyris.Crypto.Protocol.Account.AccountReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReqQueryAssetTransferHistory() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReqQueryAssetTransferHistory(ReqQueryAssetTransferHistory other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReqQueryAssetTransferHistory Clone() {
      return new ReqQueryAssetTransferHistory(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ReqQueryAssetTransferHistory);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ReqQueryAssetTransferHistory other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ReqQueryAssetTransferHistory other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
